# 启动端口
server:
  port: 8080
# 数据连接信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/base-framwork?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 自定义数据源
  application:
    name: chuyx-baseframwork

# mp配置
mybatis-plus:
  type-aliases-package: com.chuyx.pojo.*
  mapper-locations: classpath:mybatis/mapper/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出方式

# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8087/eureka/
  instance:
    instance-id: base-framword # 修改提示信息
    status-page-url: http://127.0.0.1:8080/swagger-ui.html#/