# 启动端口
server:
  port: 8080

# mp配置
mybatis-plus:
  type-aliases-package: com.chuyx.pojo.*
  mapper-locations: classpath:mybatis/mapper/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出方式